# evernote_web.yml: key to be able to read any user's data who has permitted us
username: sudtest
password: hyderabad
evernote:
  key: sudtest-7942
  secret: d89a2b1b4930c071
  options:
    client: :oauth_gem
    expose: false
    allow_login: true
    site: https://sandbox.evernote.com
    request_token_path: /oauth
    access_token_path: /oauth
    authorize_path: /OAuth.action
  
